title: World Cup Predictions bot
description: Legal policy documents for World Cup Predictions bot.
url: https://lukenamop.github.io
baseurl: /world-cup-predictions-discord-bot
theme: jekyll-theme-minimal
